source/repos/Practicalll/Practicalll/Models/Prestamo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Practicalll.Models
{
    public class Prestamo
    {
        public double Monto { get; set; }
        public int Cuotas { get; set; }
        public double Interes { get; set; }
    }
}

source/repos/Practicalll/Practicalll/Models/Transaccion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Practicalll.Models
{
    public class Transaccion
    {
        public int NoRetiro { get; set; }
        public double MontoRetiro { get; set; }
        public List<string> billetes { get; set; }

    }
}

source/repos/Practicalll/Practicalll/Pages/Cajero.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Practicalll.Models;

namespace Practicalll.Pages
{

    public class CajeroModel : PageModel
    {

        public List<Transaccion> Retiros = new List<Transaccion>();
        public string MensajeError = $"";
        int secuencia = 0;

        public Dictionary<int, int> Monedas = new Dictionary<int, int>() {
            {1000, 9},
            {500, 19},
            {100, 99}
            };


        public void OnPostSubmit(double MontoRetirar, string Banco)
        {
            double MontoDisponible = (Monedas[1000] * 1000) + (Monedas[500] * 500) + (Monedas[100] * 100);

            MensajeError = $"";

            if ((Banco == "ABC") && (MontoRetirar > 10000))
            {
                MensajeError = $"El banco ABC solo permite realizar retiros por un monto de hasta RD$ 10,000 via cajero, Verifique e intente nuevamente";
                MontoRetirar = 0;
            }

            if ((Banco != "ABC") && (MontoRetirar > 2000))
            {
                MensajeError = $"El banco Otros Bancos solo permite realizar retiros por un monto de hasta RD$ 2,000 via cajero, Verifique e intente nuevamente";
                MontoRetirar = 0;

            }

            if (MontoRetirar > 0)
            {
                if (MontoRetirar > MontoDisponible)
                {
                    MensajeError = $"No existe disponibilidad para realizar dicho retiro. Disponibilidad de RD$ {MontoDisponible:N3} , Verifique e intente nuevamente";

                }
                else
                {

                    List<string> RetirosMonedas = new List<string>();
                    Transaccion retiro = new Transaccion();
                    secuencia = Retiros.Count;
                    secuencia++;


                    retiro.MontoRetiro = MontoRetirar;
                    retiro.NoRetiro = secuencia;

                    foreach (KeyValuePair<int, int> mon in this.Monedas)
                    {
                        double disponibleMoneda = mon.Key * mon.Value;
                        int cantRebajar = 0;

                        if ((MontoRetirar > disponibleMoneda) && (disponibleMoneda > 0))
                        {
                            cantRebajar = mon.Value;
                        }
                        else
                        {
                            cantRebajar = (int)MontoRetirar / mon.Key;
                        }

                        if (cantRebajar > 0)
                        {
                            RetirosMonedas.Add($"{cantRebajar} billetes de {mon.Key}");
                        }

                        Monedas[mon.Key] -= cantRebajar;
                        MontoRetirar -= (cantRebajar * mon.Key);
                    }

                    if (RetirosMonedas.Count() > 0)
                    {
                        retiro.billetes = RetirosMonedas;
                        Retiros.Add(retiro);
                    }
                }

            }

        }

        public void OnGet()
        {

        }
    }

}

source/repos/Practicalll/Practicalll/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Practicalll.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

source/repos/Practicalll/Practicalll/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Practicalll.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

source/repos/Practicalll/Practicalll/Pages/Prestamo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Practicalll.Interfaces;
using Practicalll.Models;
using Practicalll.Services;
using Practicalll.Validations;

namespace Practicalll.Pages
{
    public class PrestamoModel : PageModel
    {
        private readonly IPrestamo _prestamoService;
        public PrestamoResult Prestamo { get; set; } = new PrestamoResult();
        public PrestamoModel(IPrestamo prestamoService)
        {
            _prestamoService = prestamoService;
        }
        public void OnGet()
        {
        }

        public void OnPost(Prestamo prestamo)
        {
            var prestamoValidator = new PrestamoValidator(prestamo);
            var result = prestamoValidator.Validate();
            if (result.IsValid)
            {
                _prestamoService.CalcularPrestamo(prestamo);
                Prestamo = _prestamoService.PrestamoResult;
            }
            else
            {
                Prestamo.ValidateResult = result;
            }
        }
    }
}

source/repos/Practicalll/Practicalll/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Practicalll.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

source/repos/Practicalll/Practicalll/Pages/Cajero.cshtml
@page
@model Practicalll.Pages.CajeroModel
@{
}

<hr />

<style scoped>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        color: black
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<h1>Cajero Automático</h1>
<table class="table table-striped">
    <tr>
        <th>Billetes: 1,000</th>
        <th>Billetes: 500</th>
        <th>Billetes: 100</th>
    </tr>
    <tr>
        <td>
            @Model.Monedas[1000] = RD$ @string.Format("{0:#,0.00}", @Model.Monedas[1000] * 1000)
        </td>
        <td>
            @Model.Monedas[500] = RD$ @string.Format("{0:#,0.00}", @Model.Monedas[500] * 500)
        </td>
        <td>
            @Model.Monedas[100] = RD$ @string.Format("{0:#,0.00}", @Model.Monedas[100] * 100)
        </td>
    </tr>
</table>
<br />
<br />

<form class="form" method="post">
    <div class="from-group">
        <div class="form-group">
            <label for="fbanco">Banco: </label>

            <select id="fbanco" name="Banco" class="form-control form-control-sm" aria-label="Default select">
                <option value="">Otro Banco</option>
                <option value="ABC">ABC</option>
            </select>

        </div>
    </div>
    <div class="form-group">
        <div class="form-group">
            <label for="fretiro">Monto Retiro: </label>
            <input type="number" id="fretiro" class="input-group" name="MontoRetirar">
        </div>
    </div>


    <input type="submit" value="Retirar" class="btn btn-info" asp-page-handler="Submit" />

</form>


<br />

@if (Model.Retiros.Count > 0)
{
    <h3>Retiros Realizados</h3>
    <table>
        <tr>
            <th>Retiro #</th>
            <th>Monto Retiro</th>
            <th>Billetes</th>
        </tr>
        @foreach (var item in Model.Retiros)
        {
            <tr>
                <td>
                    @item.NoRetiro
                </td>
                <td>
                    @string.Format("{0:#,0.00}", @item.MontoRetiro)
                </td>
                <td>
                    @foreach (var items in @item.billetes)
                    {
                        <p>@items</p>
                    }
                </td>
            </tr>
        }
    </table>
}


<br />

@if (Model.MensajeError != "")
{
    <div class="alert alert-danger">
        <p>@Model.MensajeError</p>
    </div>
}

source/repos/Practicalll/Practicalll/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

source/repos/Practicalll/Practicalll/Pages/Prestamo.cshtml
@page
@model Practicalll.Pages.PrestamoModel
@{
}
@{ string ShowMoney(double money) => $"RD{money.ToString("c")}"; }


<h1>Prestamos</h1>
<hr />

<div class="w-75 shadow-lg p-5 mb-5 bg-white rounded"
     style="margin: 0 auto">
    <form asp-route="OnCalculate" method="post">
        <h3>Calculadora de Prestamos</h3>
        <hr />
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputMonto">Monto</label>
                <input type="tel"
                       class="form-control"
                       id="inputMonto"
                       name="Monto"
                       placeholder="Ingrese el monto">
            </div>
            <div class="form-group col-md-6">
                <label for="inputCuotas">Cuotas</label>
                <input type="tel"
                       class="form-control"
                       id="inputCuotas"
                       name="Cuotas"
                       placeholder="Ingrese la cantidad de cuotas">
            </div>
            <div class="form-group col-md-6">
                <label for="inputInteres">Intereses</label>
                <input type="tel"
                       class="form-control"
                       id="inputInteres"
                       name="Interes"
                       placeholder="Ingrese el porcentaje del interes anual">
            </div>
        </div>
        <div id="result" class="m-3">
            @if (Model.Prestamo.ValidateResult.IsValid)
            {
                <div class="alert alert-success">
                    <h4>Resultados</h4>
                    <p>
                        <strong>Deuda Total:</strong> @ShowMoney(Model.Prestamo.DeudaTotal)
                    </p>
                    <p>
                        <strong>Cuota Mensual:</strong> @ShowMoney(Model.Prestamo.CoutaMensual)
                    </p>
                </div> }
            else
            {
                @if (Model.Prestamo.ValidateResult.ErrorMessage.Count() > 0)
                {
                    <div class="alert alert-danger">
                        <h4>Todos los campos son obligatorios.</h4>
                        @foreach (var error in Model.Prestamo.ValidateResult.ErrorMessage)
                        {
                            <p>@error</p>}
                    </div>          }}
        </div>
        <button type="submit" class="btn btn-outline-success btn-block">
            Calcular Cuota Mensual
        </button>
    </form>
</div>

<a href="/Index" class="btn btn-block btn-outline-info w-50" style="margin: 0 auto;">Inicio</a>

source/repos/Practicalll/Practicalll/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practicalll</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Practicalll</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Prestamo">Prestamo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cajero">Cajero</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Practicalll - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>